In [ ]:
import numpy as np
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
import numpy as np
matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
import numpy as np
np.arange(0,10)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [8]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.random.rand(5,5)

array([[0.26000374, 0.35358668, 0.88165525, 0.53450784, 0.76087008],
       [0.03373014, 0.39811791, 0.71933335, 0.97005435, 0.56627038],
       [0.85540802, 0.24861287, 0.12046136, 0.5099058 , 0.35072465],
       [0.95718935, 0.17220378, 0.39116578, 0.35402077, 0.29486365],
       [0.16198705, 0.87811272, 0.035782  , 0.87603211, 0.84594365]])

In [10]:
np.random.randint(1,100,10)


array([ 3, 10, 55, 62, 62, 51, 92, 31, 75, 84])

In [12]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)


In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
ranarr

array([39, 33, 34, 21,  6,  2, 14, 32, 25, 23])

In [15]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
ranarr.max()

np.int64(39)

In [17]:
ranarr.argmax()

np.int64(0)

In [18]:
arr.reshape(1,25).shape

(1, 25)

In [19]:
arr[1:5]

array([1, 2, 3, 4])

In [20]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [21]:
arr[arr>2]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [22]:
arr+arr

array([200, 200, 200, 200, 200,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48])

In [23]:
np.sqrt(arr)

array([10.        , 10.        , 10.        , 10.        , 10.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949])